version: "3"
services:
  frontend:
    image: udassi/frontend-client
    depends_on:
      - backend
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
  backend:
    image: backend
    environment:
      - MONGO_PASS=99Gtua8LGW7I6Xzk
